### ISSUE TITLE
update slowly

### ISSUE THREAD

**Issue by ddkwork** [richardwilkes/unison#16]
![Screenshot_20220929_204137_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/19886504/193034198-763a6920-6e09-429d-be16-88d05e04027b.jpg)

Hello you, i maked a change with button mouse entry action and add the font interface SetSize() api, when the mouse entry  font size ++, mouse exit font size --, but the ui update so slowly. Do you have any idea to me, thx.

**Comment by ddkwork** [comment]
maybe i need find some location as if type is button else the font size keep original.

**Comment by ddkwork** [comment]
> I’d have to see exactly what you were doing. Assuming you are using a hardware-accelerated display, though, it should perform well enough, depending on the other content in the window. By altering the font size, you’re likely forcing the whole window to run through layout again, which can be expensive.

![screenshots](https://user-images.githubusercontent.com/19886504/193090516-d2cca11e-64c1-469d-adcb-2442389989ea.gif)

i want get this button

**Comment by richardwilkes** [comment]
If you want the size of things to change like that, I'd recommend writing custom buttons so that you can ensure no re-layout is necessary. Otherwise, you end up doing a lot of work, which is likely slowing things down.

Anyway, that's not something I will be doing in unison, as I don't care for that style of interface. Certainly nothing stopping you from creating some custom widgets for that purpose, though.
