### ISSUE TITLE
The table dynamically increases the flashing of the row interface.

### ISSUE THREAD

**Issue by ddkwork** [richardwilkes/unison#24]
Expected dynamic addition of rows

![687474703a2f2f696d6775722e636f6d2f35385455546b562e676966.gif](https://user-images.githubusercontent.com/19886504/209701232-aea9dcc8-b614-4bf6-b105-9aeaa6fddd2d.gif)

https://user-images.githubusercontent.com/19886504/209702111-23296d21-e915-485c-9da7-8899a64c5ee5.mp4

**Comment by ddkwork** [comment]
hello again， i make a test use gcs.
![Screenshot_20221228_014435_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/19886504/209703383-a0d1a154-78ec-44e4-8cf4-1491318eda10.jpg)

I don't understand why the whole screen keeps flashing after adding lines. Another reference is to add processes to Windows Task Manager at intervals of one second. If I make a mistake, please point me out. Thank you.

**Comment by richardwilkes** [comment]
I can't really comment without seeing the actual code in question. If you're seeing any flashing at all, it's because you are doing something that causes a blank display to be generated and shown. From what little I could see in your movie above, it looked like your code was throwing exceptions regularly -- if this is happening in any of the component or render logic, that will result in a blank display since all other normal processing would have been short-circuited by the exception being thrown. Fix your code to not throw exceptions and this will not occur.
