### ISSUE TITLE
[Question] Is there an efficient way to update image or render directly to part of a window?

### ISSUE THREAD

**Issue by DatCaptainHorse** [richardwilkes/unison#43]
Been experimenting with unison along with Vulkan rendering in Go, I'm currently doing `NewImageFromPixels` each frame to update visible image on a label in window, but that can't be efficient right?

I'm not too familiar with Skia, I tried looking up ways to update the image data in a better way but couldn't find one.

Alternatively, if there's something better than image that I can copy the framebuffer data to or render to directly , I'd appreciate the knowledge and help!

**Comment by richardwilkes** [comment]
NewImageFromPixels is definitely inefficient and should be used sparingly. I don't currently have anything in Unison or the apps that I've written on top of it that try to directly use OpenGL (or in your case, Vulkan) without going through the skia layer. I would assume something similar to setting up a canvas and its surface would be what you want to do, but having not done it myself, can't say for sure.

**Comment by DatCaptainHorse** [comment]
:+1: Alright, I'll try to look around some more, thank you for response!

**Comment by ddkwork** [comment]
As far as I know, there's a mysterious bug in vulkan's window minimization behavior on Windows: swap chain stack overflow. I wrote a script to automatically simulate clicking the minimize button in order to track down the trigger of this bug, but so far it's not solved, for more tests check out the cogentcore repository!
