### ISSUE TITLE
noCgo

### ISSUE THREAD

**Issue by ddkwork** [richardwilkes/unison#61]
remove Cgo to optimize compiled binary size and compilation speed, I've made the initial bindings and rendered the window, the rest is just to bind all the macro definitions to try to replace unison's glfw3, which should theoretically reduce the compiled binary size to more than 70%, the following initial bindings are made.

https://github.com/ddkwork/app/blob/master/bindgen%2Fproject%2Fglfw%2Ftmp%2Fdemo.go

https://github.com/ddkwork/app/blob/master/bindgen%2Fproject%2Fglfw%2Ftmp%2Fglfw3.go

![625508f0-3d92-482f-8396-25886a195d79.png](https://github.com/richardwilkes/unison/assets/19886504/8142e2e8-a296-4f4a-b2f9-553b97436dc9)

**Comment by richardwilkes** [comment]
It's unclear to me how this is supposed to reduce the size of the binary. It still pulls in the same code. There might be a small reduction due to some shims not being required, but in general, there shouldn't really be much of a reduction in real code.

I can see how this might improve compile times and may make cross-compilation easier (although that remains to be seen). However, it is also likely to be extremely fragile, which is enough for me to stay away from it.

You don't state anywhere that I saw, but it looks like you're using https://github.com/gorgonia/bindgen for this. I've tinkered with such things in the past, but ultimately decided it wasn't worth the trouble. Binary size, in particular, isn't terribly important to me given the typical machine's resources nowadays.

**Comment by ddkwork** [comment]
Well, I just wanted to make some attempts

**Comment by ddkwork** [comment]
not
https://github.com/gorgonia/bindgen
now is loaddll not cgo

**Comment by richardwilkes** [comment]
Certainly no issue with you trying such things. Just wanted to let you know that I probably won't adopt them for my own stuff.

Note that loading a shared library doesn't actually save any space, since you still need to ship the shared library, too.

**Comment by ddkwork** [comment]
okay，thank



---Original---
From: "Richard ***@***.***&gt;
Date: Mon, Jul 8, 2024 00:28 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [richardwilkes/unison] noCgo (Issue #61)




 
Certainly no issue with you trying such things. Just wanted to let you know that I probably won't adopt them for my own stuff.
 
Note that loading a shared library doesn't actually save any space, since you still need to ship the shared library, too.

**Comment by ddkwork** [comment]
![screenshots](https://github.com/user-attachments/assets/beb673dc-fb28-41d2-a235-ab999ef0e296)
Experimental proof of binary reduction of 11.5 mb

**Comment by ddkwork** [comment]
I'm going to try to get unison to support android, it should be a long road, it would be nice if you could stay with me.
I'm currently using this version of glfw
https://github.com/hajimehoshi/ebiten

**Comment by ddkwork** [comment]
hyperdbg reduction of 15.9 mb
![image](https://github.com/user-attachments/assets/c0c0d7ab-00c2-4c76-ac4e-9d36e314fd35)

**Comment by richardwilkes** [comment]
Having it work on android is worthwhile. However, using dynamic libraries is not. If I had the spare time, I'd likely work on removing any last vestiges of dynamic libraries in the source (i.e. the current Go build generates binaries that have a few system dependencies that are dynamically linked... I understand there are ways to make the binary 100% static, but I've not taken the time yet to figure out how).

**Comment by ddkwork** [comment]
In any case, I'll be using today's modified cgo-free version within all my own modules, as it gives good results in terms of compilation speed and binary size

**Comment by ddkwork** [comment]
I ended up using gio to create a treeTable widget on Android, but there are still a lot of bugs to fix.

https://github.com/ddkwork/ux
